jepsen-io/maelstrom

doc/02-echo/index.md
doc/protocol.md

- Link to the echo workloads documentation was broken
- Payload didn't match accompanying text in protocol description

Fix broken link to echo workloads doc

---

doc/01-getting-ready/index.md

I assume this is a typo? Otherwise the 2 commands are the same.

Fix run from source command

---

demo/python/raft.py

* fix comment which breaks syntax highlingthing in some editors (e.g. Emacs)
* remove unsued variable from log() function

demo: fix comment in pyhon raft demo

---

demo/python/raft.py

Replace tabs with spaces in python raft demo as python3 is more strict
about mixing tabs and spaces and fails with:
$./raft.py
File "maelstrom/demo/python/./raft.py", line 42
self.next_msg_id = 0    # The next message ID we're going to allocate
TabError: inconsistent use of tabs and spaces in indentation
Mixing tabs and space should be avoid anyway.

demo: avoid mixing tabs and spaces

---

src/maelstrom/core.clj

It's possible to pass arguments for a binary which runs a node in
the db/db function, but it's not possible to specify them when running
maelstrom from command line. Parse command line for binary arguments
and add them to the list of options.

core: allow to specify argument for a binary

---

doc/04-crdts/01-g-set.md

Remove an extra `def initialize` line that seemed to only have been there by mistake

04-crdt.md Fix typo

---

README.md
doc/03-broadcast/01-broadcast.md
doc/04-crdts/02-counters.md
doc/05-datomic/01-single-node.md
doc/05-datomic/03-persistent-trees.md
doc/05-datomic/04-optimization.md
doc/06-raft/02-leader-election.md
doc/workloads.md
src/maelstrom/workload/txn_list_append.clj

Fixed some typos;
Fixed a case where the documentation incorrectly refered to the `--consistency-models` flag as `--consistency-levels`;
Added a link between CRDTs and Datomic to ease reading.
(Great docs by the way!)

Fix typos, Fix 'consistency-levels' to 'consistency-models', Add missing link

---

demo/go/cmd/maelstrom-echo/main.go
demo/go/go.mod
demo/go/node.go
demo/go/node_test.go

This pull request translates the Ruby version of `Node` into Go so that folks can integrate it into a Go workflow more easily. It includes a test suite as well as an example `echo` server. It implements message handling, initialization handling, send, reply, broadcast, & RPC.
Below is a copy of the `maelstrom-echo` Go program. It instantiates a `Node`, registers an `"echo"` message handler, and then delegates to `maelstrom.Node.Run()` for the remainder of the program.
```go
package main
import (
"encoding/json"
"log"
"os"
maelstrom "github.com/jepsen-io/maelstrom/demo/go"
)
func main() {
n := maelstrom.NewNode()
// Register a handler for the "echo" message that responds with an "echo_ok".
n.Handle("echo", func(msg maelstrom.Message) error {
// Unmarshal the message body as an …
```

Implement Node in Go

---

src/maelstrom/net.clj

This fixes a bug where Maelstrom reports the following when using the `--latency` flag:
```
java.lang.IllegalArgumentException: No matching method sleep found taking 1 args
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:154)
at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:332)
at maelstrom.net$recv_BANG_.invokeStatic(net.clj:237)
at maelstrom.net$recv_BANG_.invoke(net.clj:222)
at maelstrom.process$stdin_thread$fn__19772$fn__19773.invoke(process.clj:161)
at maelstrom.process$stdin_thread$fn__19772.invoke(process.clj:158)
at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
at clojure.lang.AFn.call(AFn.java:18)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoo …
```

Fix sleep invocation to use long type

---

demo/go/README.md
demo/go/kv.go
demo/go/node.go
demo/go/node_test.go
demo/go/rpc_error.go
demo/go/rpc_error_test.go

This pull request refactors the Go `maelstrom.Node` implementation a bit to make it more ergonomic.
- Adds a `Node.SyncRPC()` method that accepts a `context.Context` which feels more natural for Go development instead of relying on callbacks.
- Adds a `KV` client so users don't need to manually implement `read`, `write`, and `cas`.
- Adds a convenience function called `malestrom.ErrorCode()` for obtaining an RPC error code from a regular `error` type.
This also fixes some bugs like `"init"` message handling blocking which prevented KV initiation calls.

Refactor Go node implementation

---

doc/protocol.md

Hi, I'm trying to implement my own library to interoperate with maelstrom, and found out that each node has to send a response to the `init` message. This is currently not documented. I had to take a look inside the go library source code to find the expected behavior. https://github.com/jepsen-io/maelstrom/blob/main/demo/go/node.go#L182

Mention the fact that the node must respond to the init message

---

doc/protocol.md

I believe there is a typo in the init message:
```json
{
"type":     "init",
"msg_id":   1,
"node_id":  "n3",
"node_ids": ["n1", "n2", "n3"]
}
```
The `node_id` field indicates the ID of the node which is receiving this 
message: here, the node ID is "n1"
updated it to `n3`

Fix a typo

---

doc/protocol.md
resources/protocol-intro.md

Prior to this commit, the documentation gave conflicting information about which codes are reserved for Maelstrom's use and which are available for application-specific purposes. Due to a typo, the two categories had overlapping ranges.
This commit consistently specifies that codes 999 and below are reserved, while codes 1000 and above are free for application use.

Fix documentation describing reserved error codes.

---

doc/protocol.md
resources/protocol-intro.md

I'm guessing this was the typo, rather than the 1000

Fix typo in error code range.

---

pkg/maelstrom

On some systems like macOS, `/bin/bash` is not the desired Bash version. `/usr/bin/env bash` searches $PATH for Bash and can find a more recent version, like one installed via Homebrew.
Tested on Fedora Linux. (But I use `#!/usr/bin/env bash` in my Bash scripts on Macs as well)

Improve wrapper script

---

pkg/maelstrom

When working on code for one of the scenarios, for example in `~/challenge/echo`, you first have to switch to `/path/to/maelstrom` to then execute `./maelstrom ... --bin ~/challenge/echo/echo ...`.
This is a bit cumbersome, and can also lead to mixing up the proper binary path (as I did myself [here](https://github.com/jepsen-io/maelstrom/issues/42)).
With the proposed change, you can stay in `~/challenge/echo` and execute `/path/to/maelstrom/maelstrom ... --bin ./echo ...`.

Allow maelstrom to be executed from anywhere

---

pkg/maelstrom

Now the user can download the tarball, extract it wherever they want, and do:
```sh
sudo ln -s ~/maelstrom/maelstrom /usr/local/bin # as an example
maelstrom # now this will work
```
😄

Update wrapper script to account for potential symlinking

---

pkg/maelstrom

if `maelstrom` is a symlink then the wrapper script doesn't work properly.
For example, I install `maelstrom` to `~/.local/share/maelstrom` and symlink the script to `~/.local/bin`; the script as currently composed gives:
```
$ maelstrom help
Error: Unable to access jarfile ~/.local/bin/lib/maelstrom.jar
```
because it's searching in `bin` instead of `share`.
To fix it, I took the `readlink` solution from #34 and added it to the script from #46.
After applying the patch, the symlink works as expected:
```
$ maelstrom help
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.core.matrix.impl.mathsops, being replaced by: #'clojure.core.matrix.impl.mathsops/abs
Warning: protocol #'clojure.core.matrix.protocols/PMathsFunctions is overwriting function abs
WARNING: abs …
```

properly handle symlinks

---

demo/go/rpc_error.go
demo/go/rpc_error_test.go

Go framework needs to support errors nesting via "errors" package:
err = fmt.Errorf("foo: %w", error(maelstrom.NewRPCError(maelstrom.Crash, "foo")))
if maelstrom.ErrorCode(err) == maelstrom.Crash {
// do something useful
}
For checking wrapped errors returned from KV and another API that can fail due to whatever reason including context timeouts

maelstrom.ErrorCode: support errors nesting

---

demo/go/kv.go
demo/go/kv_test.go

This PR adds a simple method to the kv to read a response directly into a struct.
The current problem, that `Read` method marshals an object response into a map[string]any.

Add kv method to read into struct

---

src/maelstrom/core.clj

It was supposed to be a keyword, not a string, and now it works!
Closes #78

Fix default argument for Workload

---

demo/rust/README.md

Thank you so much for all the work on this project, I'm really enjoying going through these challenges.
What
---
Link to the implementation
Why
---
The implementation shown has compile errors
```shell
error[E0425]: cannot find function `done` in this scope
--> src/main.rs:26:9
|
26  |         done(runtime, message)
|         ^^^^
...
error[E0425]: cannot find value `message` in this scope
--> src/main.rs:26:23
|
26 |         done(runtime, message)
|                       ^^^^^^^ not found in this scope
|
```
As a follow up we could update the rest of the implementations, to link to the source code directly instead.

fix(rust): echo example

---

demo/rust/src/bin/broadcast.rs
demo/rust/src/bin/g_set.rs
demo/rust/src/bin/lin_kv.rs

Hi, in the Rust demo, I feel like the variants representing responses from the server, such as ReadOk or AddOk, would be better suited in a separate Response enum, as they are not expected from a client's request.

Separate Request and Response enums in Rust demo

---

demo/js/crdt_gset.js
demo/js/crdt_pn_counter.js
demo/js/echo.js
demo/js/echo_minimal.js
demo/js/gossip.js
demo/js/multi_key_txn.js
demo/js/node.js
demo/js/single_key_txn.js

There is no `/usr/bin/node` in recent versions of macOS so it's safer to use `/usr/bin/env node` instead. Also removed hashbang from `node.js` implementation since it's not needed.
Possibly related to #85.

Fix hashbang in JS examples
